name: Kotlin CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Build with Gradle
        uses: eskatos/gradle-command-action@v3
        with:
          gradle-version: current
          arguments: build

      - name: Run Tests with Gradle
        uses: eskatos/gradle-command-action@v3
        with:
          gradle-version: current
          arguments: test
